### ISSUE TITLE
referral

### ISSUE THREAD

**Issue by frafra077** [dj-d/AmazonPriceTracker#1]
hi, i would like to use your script, is it possible to insert a referral?

**Comment by dj-d** [comment]
Hi, could you give me an example to understand better?
Because I don't quite understand what referral is...

**Comment by dj-d** [comment]
Or rather what kind of referral you mean ...

**Comment by frafra077** [comment]
you're right I'll explain better. when the bot warns that the price has decreased it may send the product link with its amazon affiliate

**Comment by dj-d** [comment]
So would you like me to implement a classic offer channel like one that already exists and join my channel, right?

**Comment by dj-d** [comment]
Or do you want me to implement a bot where participants ask to follow a particular product and when the price of that product changes, the Amazon affiliate link is returned?

**Comment by ZappaBoy** [comment]
@ragnar-homekit If you explain what type of service you need we can implement it for you. Try to explain better you can what do you want. 

Thank's for your interesting to the project, we're happy to help the community.

**Comment by frafra077** [comment]
when the bot notifies me that the price has changed, i would like the bot to also send the amazon link with my affiliate code

**Comment by dj-d** [comment]
In the bot there is already a button that returns the URL of a specific product present in the DB, however it should not be a problem to also print the Amazon affiliate link when the price change notification arrives.

**Comment by dj-d** [comment]
But in addition to this I should make a change regarding the saving of data because, as it is structured now, every time you update the server / bot all the data in the database is lost because I use SQLite internal to the server and not in a course different. I am going to use MySQL to save the data so as to separate the server / bot from the DB

**Comment by frafra077** [comment]
yes the best thing is to use mysql in this way the data should not be deleted

**Comment by dj-d** [comment]
Hi, I added the functionality in a separate branch, for any problem contact me
