### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Loki-it** [dj-d/AmazonPriceTracker#2]
Hello!
I tried your script but personally it doesn't work
(I tried both from windows and linux, both with the libraries inside the requirements.txt and in the updated ones, both with docker and without docker but it doesn't seem to work)

I wanted to write you in private but I can't find your contacts on Github, in case I leave you my contact on Discord> Loki#5537
P.s if you are Italian I am happy to write you in Italian, my English is very bad

**Comment by dj-d** [comment]
Ciao, 
Hai problemi con lo script presente in master o con gli script in dbChange?

**Comment by dj-d** [comment]
Ti ho inviato anche l'amicizia su Discord visto che non posso mandarti messaggi senza essere amici. Se vuoi, possiamo parlare anche lì.

**Comment by Loki-it** [comment]
Eccomi, ho accettato la richiesta di amicizia!
Sono disponibile quando vuoi per discuterne

**Comment by dj-d** [comment]
It's not a system problem but it's Amazon that blocks requests. I'll find the solution as soon as I can.
